base_url = "https://janneskelso.com"
compile_sass = true
title = "Jannes Kelso"
# description = "A clean blogging theme"

[extra]
hyde_sticky = false
hyde_theme = "theme-base-00"
hyde_links = [
    {url = "https://janneskelso.com/posts", name = "Posts"},
    {url = "https://janneskelso.com/resume", name = "Resume"},
    {url = "https://janneskelso.com", name = "About"},
]
# footer = ""